### ISSUE TITLE
How to close notification manually if website is open and push click

### ISSUE THREAD

**Issue by ipehimanshu** [Pushwoosh/web-push-notifications#26] opened 2021-07-19 07:45 UTC
Hello

We need to manually close notification when user click on notification and say user already open that website or page then just focus window,
we are passing link parameter so here issue is even website open then push click open again new tab.

Thanks

**Comment by wfhm** [comment] 2021-07-20 05:25
@ipehimanshu I am sorry for the original message, the bot that links Github issues with our internal tracker messed up a bit.

I'll check it with the Web SDK team and update this thread shortly.

**Comment by ipehimanshu** [comment] 2021-07-20 09:35
yes true we don't want to open new tab when someone click on push, like
website already open so we want to catch some event

**Comment by wfhm** [comment] 2021-07-20 10:19
@ipehimanshu,

Will be done in the next couple of days, I will follow up when it is released.

**Comment by ipehimanshu** [comment] 2021-07-20 16:03
ok thanks sir

**Comment by wfhm** [comment] 2021-07-21 10:51
@ipehimanshu the fix is in production now. Please let us know if the issue persists.

**Closed as completed by wfhm** 2021-07-21 10:51 UTC
Labels: 61887

**Comment by ipehimanshu** [comment] 2021-07-21 12:32
@wfhm 
here is what i see when click on push

![image](https://user-images.githubusercontent.com/26652038/126488452-3c355bfa-042b-41c7-98d4-b1c2ecb97c13.png)

and it open new tab into my chrome browser with url.

So please let me know what i need to add or change ?

I am using latest 

![image](https://user-images.githubusercontent.com/26652038/126488799-c5efd811-4f2b-48dc-ac7e-5c4bbfb967de.png)


Thanks

**Comment by wfhm** [comment] 2021-07-22 05:13
@ipehimanshu We could not reproduce the issue after the fix. Can you show us where exactly the error happens? Also, what is the link that you send with a push?  What is the version of Pushwoosh service worker?

**Comment by ipehimanshu** [comment] 2021-07-22 12:03
@wfhm 
can you share email so i can share more information as some information i can not share as public.
And regarding version, so please see 
https://user-images.githubusercontent.com/26652038/126488799-c5efd811-4f2b-48dc-ac7e-5c4bbfb967de.png
it is something 3.21.0
Thanks

**Comment by wfhm** [comment] 2021-07-22 12:25
@ipehimanshu you can contact me at help@pushwoosh.com directly, so we can continue the troubleshooting using emails.
